### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ashi360** [echau01/Canvas-Tracker#1]
Hey, when running the code with python main.py I get this error.

`Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/DateBotCanvas/commands.py", line 11, in <module>
    import periodic_tasks
  File "/home/runner/DateBotCanvas/periodic_tasks.py", line 26, in <module>
    CANVAS_INSTANCE = Canvas(CANVAS_URL, CANVAS_TOKEN)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/canvasapi/canvas.py", line 58, in __init__
    access_token = access_token.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 18, in <module>
    bot.load_extension("commands")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'commands' raised an error: AttributeError: 'NoneType' object has no attribute 'strip'`

Any help would be grateful.

**Comment by echau01** [comment]
Did you put a Canvas user token in your `.env` file? See the installation instructions.

**Comment by Ashi360** [comment]
Yea give me a few hours and I'll record what I got.

**Comment by Ashi360** [comment]
https://www.loom.com/share/8ef75dfa6f054c528b2a00fbee81bda2

Hope this is better. It gives a new error now.

**Comment by echau01** [comment]
Thank you, I saw your comment. But **please do not post your Discord token or Canvas token publicly.** They are meant to be like passwords. That's why I had to delete your comment.

Nevertheless, I'm investigating the issue.

**Comment by Ashi360** [comment]
Ahh, good to know thanks. 🙏🙏

**Comment by echau01** [comment]
It seems that repl.it refuses to load environment variables from `.env` if you run from the shell. For me, it works if you run the bot by pressing the Run button. Can you try that?

**Comment by Ashi360** [comment]
Nope, just wondering you ran it on Microsoft code?

**Comment by echau01** [comment]
It doesn't work when you press the big Run button at the top of repl.it? That's strange.

I run the bot in a Windows cmd.exe terminal on my local machine. You can certainly run it from VSCode too.

**Comment by Ashi360** [comment]
https://www.loom.com/share/7c5499a50a414e2ea80857c9c6d0890f

**Comment by echau01** [comment]
I found some discussion of this error happening if you run on Python 3.9. (For reference, I use Python 3.8.) However, I think this error has been fixed for the new discord.py version (version 1.6.0). I have just updated the discord.py version in the requirements.txt, so could you try pip installing again?

**Comment by Ashi360** [comment]
^^ I was just on that ima uninstall 3.9 and install 3.8.

**Comment by Ashi360** [comment]
Welp, I tried lol, but uhh it doesn't work the only way I have gotten it to work if I delete the .env file and place my token inside the proper parenthesis. But it should be fine as I can run it on my local pc. Just wondering is there a way you can run this offline as well? Like if I decide to turn off my computer the bot can still be active?

**Comment by echau01** [comment]
I always run the bot on my PC. I don't know a way to keep it alive forever, but I made a startup script that automatically launches the bot when I turn on my PC. [I see you're using Windows, so make a task in Task Scheduler that starts the bot when you log in.]

Also, I found out how to reproduce the error you're talking about on repl.it, so I'll investigate that.

**Comment by Ashi360** [comment]
🙏
